#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 185

#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 180000

#undef RGB_MATRIX_VAL_STEP
#define RGB_MATRIX_VAL_STEP 1

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Lz7KX/zLQomJ"
#define LAYER_STATE_8BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

