#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 180000

#undef RGB_MATRIX_VAL_STEP
#define RGB_MATRIX_VAL_STEP 1

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Lz7KX/RjgaRW"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1

#define RGB_MATRIX_STARTUP_SPD 60

